In [1]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures
from sklearn.preprocessing import OrdinalEncoder , StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [2]:
df=pd.read_csv("ai-impact-jobs-layoff-risk-dataset.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=20000, step=1)
All columns are
0 Age
1 Education_Level
2 Years_of_Experience
3 Industry
4 Job_Role
5 Company_Size
6 Job_Level
7 Routine_Task_Percentage
8 Creativity_Requirement
9 Human_Interaction_Level
10 AI_Adoption_Level
11 Number_of_AI_Tools_Used
12 AI_Usage_Hours_Per_Week
13 Tasks_Automated_Percentage
14 AI_Training_Hours
15 Layoff_Risk

In [3]:
df.head(n=10)

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6,Finance,Accountant,Medium,Entry,84,21,94,Medium,5,7,40,26,High
1,44,Master's,14,Manufacturing,Production Supervisor,Small,Entry,30,84,68,Low,2,2,14,9,Low
2,36,Bachelor's,7,Retail,Store Manager,Medium,Senior,12,86,71,Low,0,1,6,3,Low
3,27,Bachelor's,6,Finance,Auditor,Large,Entry,90,18,21,Medium,3,10,67,26,High
4,49,High School,12,Finance,Auditor,Small,Entry,49,52,72,Medium,5,13,26,19,Medium
5,45,PhD,9,Telecom,Network Engineer,Large,Entry,72,33,54,Medium,4,5,69,9,High
6,48,Bachelor's,10,IT,Software Engineer,Small,Entry,46,63,63,Medium,2,7,45,9,Medium
7,23,Master's,2,Retail,Store Manager,Medium,Mid,36,37,77,Low,2,0,27,3,Medium
8,24,Bachelor's,3,IT,ML Engineer,Large,Entry,41,62,90,Low,1,1,20,8,Low
9,48,Master's,6,Retail,Inventory Analyst,Small,Senior,84,8,81,Medium,2,5,67,29,Medium

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  object
dtypes: int64(9), object(7)
memory usage: 2.4+ MB

In [5]:
for col in df.select_dtypes(include=['object', 'category']):
    print(df[col].value_counts())
    print("-" * 20)  # Separator line

Education_Level
Bachelor's     9967
Master's       5426
High School    3558
PhD            1049
Name: count, dtype: int64
--------------------
Industry
Telecom          2582
Healthcare       2561
Finance          2513
Logistics        2488
IT               2483
Retail           2467
Manufacturing    2457
Education        2449
Name: count, dtype: int64
--------------------
Job_Role
Nurse                    900
Medical Assistant        889
Financial Analyst        879
Support Specialist       873
Network Engineer         862
Operator                 858
Inventory Analyst        857
Supply Chain Analyst     857
Data Analyst             849
Operations Analyst       847
Warehouse Manager        843
Software Engineer        829
Accountant               821
Academic Coordinator     819
Research Assistant       818
Auditor                  813
Teacher                  812
Sales Associate          807
Production Supervisor    806
ML Engineer              805
Store Manager            803
Quality Engineer         793
Dispatcher               788
Health Analyst           772
Name: count, dtype: int64
--------------------
Company_Size
Medium    8964
Small     6066
Large     4970
Name: count, dtype: int64
--------------------
Job_Level
Entry     9016
Mid       7940
Senior    3044
Name: count, dtype: int64
--------------------
AI_Adoption_Level
Low       10539
Medium     8046
High       1415
Name: count, dtype: int64
--------------------
Layoff_Risk
High      6797
Low       6602
Medium    6601
Name: count, dtype: int64
--------------------

In [6]:
df.columns

Index(['Age', 'Education_Level', 'Years_of_Experience', 'Industry', 'Job_Role',
       'Company_Size', 'Job_Level', 'Routine_Task_Percentage',
       'Creativity_Requirement', 'Human_Interaction_Level',
       'AI_Adoption_Level', 'Number_of_AI_Tools_Used',
       'AI_Usage_Hours_Per_Week', 'Tasks_Automated_Percentage',
       'AI_Training_Hours', 'Layoff_Risk'],
      dtype='object')

In [7]:
# Removing null values
df = df.dropna()
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  object
dtypes: int64(9), object(7)
memory usage: 2.4+ MB
None

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  object
dtypes: int64(9), object(7)
memory usage: 2.4+ MB

In [9]:
# shuffling the whole dataset 
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
df.head()

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,46,Master's,17,Healthcare,Nurse,Large,Senior,69,48,76,Low,1,2,65,1,Low
1,46,High School,4,Healthcare,Nurse,Medium,Senior,32,60,98,Low,0,1,19,6,Low
2,38,Bachelor's,10,Telecom,Support Specialist,Large,Mid,44,63,79,Medium,3,12,36,19,Low
3,41,Bachelor's,4,Education,Teacher,Large,Senior,16,95,84,Low,2,2,11,2,Low
4,57,High School,5,Telecom,Support Specialist,Large,Senior,26,72,59,Low,0,3,13,1,Low

In [11]:
le = LabelEncoder()
df['Layoff_Risk'] = le.fit_transform(df['Layoff_Risk'])
print(df['Layoff_Risk'])

0        1
1        1
2        1
3        1
4        1
        ..
19995    0
19996    2
19997    2
19998    0
19999    1
Name: Layoff_Risk, Length: 20000, dtype: int64

In [12]:
X = df.drop(['Layoff_Risk'],axis = 1)
y = df['Layoff_Risk']
print(X.columns)
print(y)

Index(['Age', 'Education_Level', 'Years_of_Experience', 'Industry', 'Job_Role',
       'Company_Size', 'Job_Level', 'Routine_Task_Percentage',
       'Creativity_Requirement', 'Human_Interaction_Level',
       'AI_Adoption_Level', 'Number_of_AI_Tools_Used',
       'AI_Usage_Hours_Per_Week', 'Tasks_Automated_Percentage',
       'AI_Training_Hours'],
      dtype='object')
0        1
1        1
2        1
3        1
4        1
        ..
19995    0
19996    2
19997    2
19998    0
19999    1
Name: Layoff_Risk, Length: 20000, dtype: int64

In [13]:
# Direct without category
X = df.drop(['Layoff_Risk'],axis = 1)
y = df['Layoff_Risk']
X = X.drop(columns = df.select_dtypes(include='object').columns)


Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2,random_state=42)


model = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LogisticRegression())
])


model.fit(Xtrain, ytrain)


ypred = model.predict(Xtest)


print("Accuracy Score:", accuracy_score(ytest, ypred))

Accuracy Score: 0.7245

In [14]:
scores = cross_val_score(model,X,y,cv=10,scoring="accuracy")
print("Accuracy:", scores)
print("Mean accuracy:", scores.mean())

Accuracy: [0.7305 0.7185 0.7205 0.719  0.718  0.741  0.7235 0.727  0.721  0.7075]
Mean accuracy: 0.72265

In [15]:
print(X.columns)

Index(['Age', 'Years_of_Experience', 'Routine_Task_Percentage',
       'Creativity_Requirement', 'Human_Interaction_Level',
       'Number_of_AI_Tools_Used', 'AI_Usage_Hours_Per_Week',
       'Tasks_Automated_Percentage', 'AI_Training_Hours'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  int64
dtypes: int64(10), object(6)
memory usage: 2.4+ MB

In [17]:
df.columns

Index(['Age', 'Education_Level', 'Years_of_Experience', 'Industry', 'Job_Role',
       'Company_Size', 'Job_Level', 'Routine_Task_Percentage',
       'Creativity_Requirement', 'Human_Interaction_Level',
       'AI_Adoption_Level', 'Number_of_AI_Tools_Used',
       'AI_Usage_Hours_Per_Week', 'Tasks_Automated_Percentage',
       'AI_Training_Hours', 'Layoff_Risk'],
      dtype='object')

In [18]:
le = LabelEncoder()
df['Layoff_Risk'] = le.fit_transform(df['Layoff_Risk'])
print(df['Layoff_Risk'])

0        1
1        1
2        1
3        1
4        1
        ..
19995    0
19996    2
19997    2
19998    0
19999    1
Name: Layoff_Risk, Length: 20000, dtype: int64

In [19]:
n = df.select_dtypes(include=['number']).columns.tolist()

non = df.select_dtypes(exclude=['number']).columns.tolist()

print(n)
print(non)

['Age', 'Years_of_Experience', 'Routine_Task_Percentage', 'Creativity_Requirement', 'Human_Interaction_Level', 'Number_of_AI_Tools_Used', 'AI_Usage_Hours_Per_Week', 'Tasks_Automated_Percentage', 'AI_Training_Hours', 'Layoff_Risk']
['Education_Level', 'Industry', 'Job_Role', 'Company_Size', 'Job_Level', 'AI_Adoption_Level']

In [20]:

X = df.drop("Layoff_Risk", axis=1)
y = df["Layoff_Risk"]


Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2)


numeric_cols = X.select_dtypes(include='number').columns

categorical_cols = X.select_dtypes(include='object').columns


preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)


model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])


model.fit(Xtrain, ytrain)


ypred = model.predict(Xtest)

print("Accuracy:", accuracy_score(ytest, ypred))


scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print(scores)
print("Mean accuracy:", scores.mean())

Accuracy: 0.93175
[0.94175 0.93625 0.93425 0.93875 0.943  ]
Mean accuracy: 0.9388